### PR TITLE
Upstream/zl/master to basho master

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
As per discussions w/ @JeetKunDoug and keeping webmachine up to date.

### CODE REVIEW

**Comment by bsparrow435** [comment]
@JeetKunDoug thoughts on merging this?

**Comment by JeetKunDoug** [comment]
Before merging, we need to make sure that Riak 2.2 won't take these changes - if you can confirm we're pegged to a tag under our control and that these commits won't come in until we get passed release, +1. Otherwise, let's hold off.

**Comment by lukebakken** [comment]
@JeetKunDoug - yep, there are only two deps that use `webmachine`, and they use the `1.10.8-basho1` tag. This is from the `riak_ee-2.2.0encap8` tag after running `make locked-deps rel` (edited out non-dep lines):

```
$ find . -type f -name rebar.config -exec fgrep webmachine {} +
./deps/riak_api/rebar.config:        {webmachine, "1.10.8", {git, "git://github.com/basho/webmachine.git", {tag, "1.10.8-basho1"}}},
./deps/riak_control/rebar.config:       {webmachine, "1.10.8", {git, "git://github.com/basho/webmachine.git", {tag, "1.10.8-basho1"}}},
```

**Comment by JeetKunDoug** [comment]
Thanks for confirmation. +1

**Pull request merged**
