### PR TITLE
Update to README based on new org status

### PR DESCRIPTION
**Pull request by mbbroberg**
Clarifies that Basho started this project and @seancribbs is organizing the go-forward efforts.

### CODE REVIEW

**Comment by mbbroberg** [comment]
What do you think of the wording @seancribbs and @laurenrother? After this I'll open a PR to upstream.

**Comment by seancribbs** [comment]
I appreciate the shoutout but I don't think it's necessary. Also, should I ever be unable to contribute, the bus factor might be too low. Better just to leave out specific names and refer people to the organization.

**Comment by lrnrthr** [comment]
It sounds good, though I think the contact information is crucial to not leaving the user in the dust with the change. That said, given @seancribbs comment, I'm not sure where you should link them to. Is there a webpage or git repo for that new org?

**Comment by mbbroberg** [comment]
Hey @seancribbs, while I respect the bus factor, it's also for clarity of leadership. I'm glad to point to a larger organization once you've established something. Until then, no playing in traffic please. :+1:

**Pull request merged**
